# deployment and service for mongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  #replicas = how many pods to create
  replicas: 1
  selector:
    #selector checks that all labels with the same match
    #label will belong to the same deployment
    matchLabels:
      app: webapp
  #template is the blueprint of pod(s)    
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0 #node.js app
        ports:
        #port for mongodb
        - containerPort: 3000
        env:
        - name: USER-NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER-PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
#yaml syntax with three dashes to seperate a file into two
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #targetport should be the same as container port
      #targetport will fwd services to containerport
      nodePort: 30100